bitrise-io/bitrise-init

- models/models.go
- scanners/ios/ios.go
- steps/steps.go
new ios workflows, step version updates
> format version update to 1.3.0, trigger map format update, 

- _tests/integration/android_test.go
- _tests/integration/mac_test.go
- scanner/config.go
- scanner/manual_config.go
- scanners/android/android.go
- scanners/scanners.go
* removed install of `extra-android-support`
* centralised active scanners (`scanners.ActiveScanners`)
* disable macos scanner
> Android deps

- _tests/integration/ios_test.go
- scanners/ios/ios.go
- scanners/macos/macos.go
previous link (official apple link) no longer exists
new link points to our DevCenter
> shared scheme link fix

- _tests/integration/ios_test.go
- _tests/integration/manual_config_test.go
- _tests/integration/reactnative_test.go
- scanners/ios/utility.go
- scanners/reactnative/reactnative.go
- scanners/reactnative/utility.go
- steps/const.go
- steps/steps.go
- removed install-react-native step
- updated react-native config names
- ios config without test update
> react native scanner updates

- README.md
- scanners/scanners.go
- described how to build/test this project locally in README file. Should be useful for new contributors.
- (additionally) fixed few typo's in `scanners.go`
> Add how to build section to README

- steps/const.go
- version/version.go
> release 2.1.1

- maintenance/maintenance_test.go
- steps/const.go
- change default step versions to lock on major version
- fix ci: missing stack
> Tool 1345 lock to major step versions

- maintenance/maintenance_test.go
- steps/const.go
* fix: update stack list with xcode 11.3
* change version strings, declare major version only
> Tool 1345 lock to major step versions (#177)

- steps/const.go
New major versions are available for Xcode Archive and Expo Detach steps.
Ticket: [STEP-251](https://bitrise.atlassian.net/browse/STEP-251)
- Update Xcode Archive and Expo Detach steps major version.
> Update step versions to latest major.

- _tests/integration/ios_test.go
- steps/const.go
Update step versions to latest major:
- [Fastlane@3](https://github.com/bitrise-steplib/steps-fastlane/releases/tag/3.0.0)
- [Git Clone@5](https://github.com/bitrise-steplib/steps-git-clone/releases/tag/5.0.0)
- [Flutter Test@1](https://github.com/bitrise-steplib/bitrise-step-flutter-test/releases/tag/1.0.0)
Fix `sampleAppClip` test case.
> Step 861 update step versions

- version/version.go
- Update version based on the upcoming release.
> Bump version.

- steps/const.go
- version/version.go
Step release: https://github.com/bitrise-steplib/bitrise-step-android-build/releases/1.0.0
> Update Android Build step to 1.x

- _tests/integration/android_test.go
- _tests/integration/manual_config_test.go
- scanner/config.go
- scanner/result.go
- scanners/android/android.go
- scanners/android/const.go
- scanners/android/utility.go
- scanners/cordova/cordova.go
- scanners/fastlane/fastlane.go
- scanners/flutter/flutter.go
- scanners/ionic/ionic.go
- scanners/ios/ios.go
- scanners/ios/podfile_test.go
- scanners/macos/macos.go
- scanners/reactnative/reactnative.go
- scanners/scanners.go
- steps/steps.go
Updated Android deploy WF.
Resolves: https://bitrise.atlassian.net/browse/STEP-1747
- Introduces the isPrivateRepo paramter in the Config method of ScannerInterface.
- Fixed an unrelated Cocoapods test.
> Update Android deploy WF

- _tests/integration/android_test.go
- _tests/integration/manual_config_test.go
- scanners/android/const.go
- scanners/android/utility.go
Updated Android primary WF.
Resolves: https://bitrise.atlassian.net/browse/STEP-1748
- Reorganized initial primary workflow, added description.
> Updated Android primary workflow

- _tests/integration/manual_config_test.go
- _tests/integration/reactnative_expo_test.go
- _tests/integration/reactnative_test.go
- scanners/reactnative/const.go
- scanners/reactnative/expo.go
- scanners/reactnative/plain.go
Updated react-native and Expo workflow descriptions.
Resolves
https://bitrise.atlassian.net/browse/STEP-1744
https://bitrise.atlassian.net/browse/STEP-1742
> Update react-native workflow descriptions

- .gitignore
- _tests/integration/android_test.go
- _tests/integration/cordova_test.go
- _tests/integration/fastlane_test.go
- _tests/integration/flutter_test.go
- _tests/integration/ionic_test.go
- _tests/integration/ios_test.go
- _tests/integration/mac_test.go
- _tests/integration/manual_config_test.go
- _tests/integration/reactnative_expo_test.go
- _tests/integration/reactnative_test.go
- models/configbuilder.go
- models/configbuilder_test.go
- Remove workflow trigger map
- Added tests
> Remove workflow trigger map

- steps/const.go
Updated const.go file with the latest version:
- InstallMissingAndroidToolsVersion
- cordova-archive
> Updated const.go file

- go.mod
- go.sum
- scanners/ios/appclip.go
Updates `go-xcode` to pull the following change: https://github.com/bitrise-io/go-xcode/pull/167
> Update go-xcode, optimize target parsing

- bitrise.yml
- go.mod
- steps/const.go
- Bump git clone step version
- Cleanups and housekeeping
> Bump git clone step major version

- _tests/integration/ios_test.go
- _tests/integration/manual_config_test.go
- scanners/ios/spm.go
- scanners/ios/spm_test.go
- scanners/ios/utility.go
- scanners/ios/utility_test.go
- scanners/ios/workflow.go
- scanners/reactnative/plain.go
- steps/cachesteps.go
- steps/const.go
- Detect SPM usage in the project scanning phase
- Add SPM cache steps in the workflow generation phase
> Detect SPM usage, add SPM cache steps

- _tests/integration/cordova_test.go
- _tests/integration/fastlane_test.go
- _tests/integration/flutter_test.go
- _tests/integration/ionic_test.go
- _tests/integration/manual_config_test.go
- models/configbuilder_test.go
- scanners/android/utility.go
- scanners/cordova/cordova.go
- scanners/fastlane/fastlane.go
- scanners/flutter/flutter.go
- scanners/ionic/ionic.go
- scanners/ios/workflow.go
- scanners/reactnative/expo.go
- scanners/reactnative/plain.go
- scanners/scanners.go
- steps/cachesteps.go
- steps/const.go
- steps/steps.go
- Replace legacy cache steps with new steps in Flutter workflows
- Clean up the last remaining references to the legacy cache steps
- Clean up the duplicated prepare and deploy functions as the old ones are not used anymore
> Flutter cache steps, cleanup legacy cache steps

- steps/const.go
> Updated xcode-test version.

- _tests/integration/android_test.go
- _tests/integration/cordova_test.go
- _tests/integration/helper/validation.go
- _tests/integration/ionic_test.go
- _tests/integration/manual_config_test.go
- _tests/integration/nodejs_test.go
- _tests/integration/reactnative_expo_test.go
- _tests/integration/reactnative_test.go
- go.mod
- scanners/cordova/cordova.go
- scanners/ionic/ionic.go
- scanners/nodejs/nodejs.go
- scanners/nodejs/utiltity.go
- scanners/reactnative/reactnative.go
- scanners/scanners.go
- steps/const.go
- steps/steps.go
- utility/utility.go
Requires a *MAJOR/MINOR/PATCH* [version update](https://semver.org/)
> nodejs-scanner
