bitrise-io/bitrise-init

- scanners/android/android.go
Scanner (or somewhere else? e.g. in Gradle Runner?): warning if Android `local.properties` is committed into the repo
If the local.properties file is committed into the repo you'll get an error for any Android/Gradle build like:
```
* What went wrong:
A problem occurred configuring project ':app'.
> The SDK directory '/Users/rodrigosimoesrosa/Library/Android/sdk' does not exist.
```
Note the directory path -> it's the path __on the user's Mac!__
> error if Android `local.properties` is committed into the repo - completed

- _tests/integration/android_test.go
- _tests/integration/cordova_test.go
- _tests/integration/fastlane_test.go
- _tests/integration/flutter_test.go
- _tests/integration/ionic_test.go
- _tests/integration/ios_test.go
- _tests/integration/mac_test.go
- _tests/integration/reactnative_expo_test.go
- _tests/integration/reactnative_test.go
- _tests/integration/xamarin_test.go
- errormapper/errormapper.go
- errormapper/errormapper_test.go
- models/models.go
- scanner/config.go
- scanner/config_test.go
- scanner/errors.go
- scanner/errors_test.go
- scanner/result.go
- step/steperror.go
Map bitrise-init errors.
- first merge [git-clone step PR](https://github.com/bitrise-steplib/steps-git-clone/pull/126)
- use git-clone step's `errormapper` package rather than duplicating the generic error mapper functionality
- `models.Recommendation` needs to be moved back to `step` package
> Act 630 decorate errors

- errormapper/errormapper.go
- errormapper/errormapper_test.go
- scanner/errors.go
PatternErrorMatcher.Run passes the original error message to DetailedErrorBuilders,
so that DetailedErrorBuilders can use the original error message.
> errormapper package update

- analytics/analytics.go
- analytics/analytics_test.go
- scanners/android/android.go
- scanners/android/icon.go
- scanners/android/icon_test.go
- If icon format is unsupported, does not fail, instead returns default icons.
- Send failures to analytics Info level log, does not return warnings to user
> Ignoring Android scanner errors resulting from icon lookup failures.

- analytics/analytics.go
- scanner/config.go
- scanners/ios/utility.go
Supressing ios icon lookup failures.
Sending warnings returned by Options to analytics.
> Act 902 supress ios icon errors

- scanners/android/android.go
- scanners/android/utility.go
- scanners/android/utility_test.go
* Unified gradle file lookup
* Written tests
* Only fail android project scanner if not other project is found proper
> Ignore Android project scanner errors if we find an other proper project

- maintenance/maintenance_test.go
- scanner/config.go
- scanner/errors.go
- scanners/ionic/ionic.go
- scanners/ionic/utility.go
1. Having cordova.xml is not mandatory anymore for Ionic projects, but if it's missing we show a warning message to the user that atm we only support Ionic Cordova projects.
2. Adding warningsWithRecommendation and errorsWithRecommendation to the not detected projects' output.
Users will see the following while trying to add an Ionic Capacitor project:
> Showing a better error message to Ionic Capacitor users

- .gitignore
- Gopkg.lock
- _tests/integration/ios_test.go
- scanners/ios/utility.go
- scanners/ios/utility_test.go
- steps/const.go
- steps/steps.go
- vendor/github.com/bitrise-io/go-xcode/xcodeproj/xcscheme.go
- vendor/github.com/bitrise-io/go-xcode/xcodeproj/xctarget.go
- vendor/github.com/bitrise-io/go-xcode/xcodeproj/xctarget_test_files.go
Add support for AppClips in ProjectScanner. If AppClip is detected the generated workflow contains a step to export it along the app.
[STEP-87](https://bitrise.atlassian.net/browse/STEP-87)
- Do *NOT* check `/vendor` folder
- Add export appclip step where applicable.
- Added new test case (`sample-apps-appclip`) to `ios_test.go` and refectored to table tests.
- Exporting appclip is only applicable for `development` and `ad-hoc` export methods.
> Detect iOS AppClips in ProjectScanner

- .gitignore
- maintenance/maintenance_test.go
- steps/const.go
- version/version.go
**Bump Xcode Test for iOS step to 3.0.0**
* Cleaned up test error messages regarding stacks.
> Bump Xcode Test for iOS step to 3.0.0

- _tests/integration/android_test.go
- _tests/integration/manual_config_test.go
- scanners/android/utility.go
- version/version.go
* When a new Android app is added to Bitrise, we create default workflows for the user: `primary` and `deploy`.
* In these workflows we use the Android Lint and Android Unit Test steps, where the `Module` input is set to `$MODULE`. This means tests and lint checks will only be performed against the module that was specified by the user when the project's Bitrise config was generated (e.g. when the app was added to Bitrise).
* In multi-module Android projects, unit tests and lint issues can be in multiple modules, not just in the one that was initially provided by the user.
* Therefore, it doesn't make much sense to run lint checks and unit tests only in that module by default.
* Do not specify any modules in the generated workflows' Android Lint and Android Unit Test steps.
> Do not specify module in Android Lint and Android Unit Test

- scanners/android/android.go
I was troubleshooting the project scanner, and it was unclear to me if the android project scanner found any files. This PR adds some log statements to make this easier to quickly get info.
> Adds Log Statements to Android Project Scanner

- _tests/integration/android_test.go
- _tests/integration/fastlane_test.go
- _tests/integration/helper.go
- _tests/integration/ios_test.go
- _tests/integration/mac_test.go
- _tests/integration/manual_config_test.go
- scanners/ios/appclip.go
- scanners/ios/ios.go
- scanners/ios/utility.go
- scanners/ios/workflow.go
- scanners/macos/macos.go
- steps/const.go
- steps/steps.go
Tickets:
- https://bitrise.atlassian.net/browse/STEP-1750
- https://bitrise.atlassian.net/browse/STEP-1749
Changes:
- Appclip related logic is extracted to a dedicated file
- The workflow generation is also extracted into a separate file
- The three different hard coded paths are unified
- The common elements are shared between the two workflows
- Xcode build for test step is added 
- The integration tests are updated to reflect the changes
> [STEP-1750 & STEP-1749] Update iOS default workflows

- _tests/integration/reactnative_expo_test.go
- _tests/integration/reactnative_test.go
- scanners/ios/utility.go
- scanners/reactnative/const.go
- scanners/reactnative/plain.go
- scanners/reactnative/reactnative.go
- [-] `step.yml` and `README.md` is updated with the changes (if needed)
Requires a *MINOR* [version update](https://semver.org/)
Updates react-native workflows:
- Includes _npm_/_yarn_ `test` in **deploy** workflow
- **primary** and **deploy** workflow always created. If tests are not found in the project **primary** workflow contains _npm_/_yarn_ `install` only, but not building the native apps. Previously **primary** took **deploy**'s place in these cases.
- Empty Script Step removed
- _Certificate and profile installer_ Step removed, _Xcode Archive & Export for iOS_'s Automatic code signing option is enabled instead.
- Fixes issue with an invalid workflow generated for projects without tests. (The same logic as for tests is used.)
Resolves …
> Updating react-native workflows

- _tests/integration/flutter_test.go
- _tests/integration/manual_config_test.go
- scanners/flutter/const.go
- scanners/flutter/flutter.go
Update the primary Flutter workflow creation by removing some steps and simplifying detection.
- Remove Script step in all possible cases
- Remove Flutter Analyze step in all possible cases
- Add primary workflow description
- Don't ask the user about the presence of tests. This information is detected by the scanner and we can insert/omit the Flutter Test step just like before.
- Don't insert SSH key step if the Git repo is public (as it's not needed for public repos)
- Swap Cache Push and Deploy to Bitrise.io steps
See my line-by-line comments in the diff view
> Update Flutter primary workflow

- scanners/ios/podfile.go
- scanners/ios/rubyscript.go
- scanners/ios/rubyscript_test.go
Resolves: https://bitrise.atlassian.net/browse/STEP-1742
Set the temp dir as working dir, so the project defined `.ruby-version` does not cause ruby resolution to fail:
``` [ ... ] ruby script failed, error: rbenv: version `2.7.4' is not installed (set by /[ ... ]/MyTestApp/.ruby-version)```
- Removed *runRubyScriptForOutput* _inDir_ parameter
- Improved error messages
> Fix missing Ruby during react-native Podfile detection

- _tests/integration/flutter_test.go
- _tests/integration/manual_config_test.go
- scanners/flutter/const.go
- scanners/flutter/flutter.go
Updating and simplifying the Flutter workflows. Follow-up to #223 
- Remove Xcode archive step from the workflow as the Flutter build command has this functionality now for a while
- Set `ios_build_type` to `archive` in the Flutter build step if platform is `ios` or `both` to build an xcarchive
- Remove empty Script step
- Remove scanner options related to the Xcode archive step, such as the distribution method. These options are no longer needed, because the Xcode Archive step is removed, plus the deploy workflow needs some manual configuration anyway before the first successful build
- Add workflow description
> Update Flutter deploy workflow

- scanner/config_test.go
- scanner/errors.go
- scanner/errors_test.go
- scanners/android/android.go
- scanners/android/android_test.go
- scanners/android/utility.go
- scanners/reactnative/plain.go
- scanners/reactnative/reactnative.go
Separated Android project parsing in a separate phase, independent of _Options()_.
This allows reuse of the code in the react-native scanner, and can be tested independently of config generation.
* Extracted Android project parsing from Options() to parseProjects()
* react-native  options generation no longer reuses Android Options(), this allows for leaving out unused questions.
> Separate android project parsing

- scanners/ios/ios.go
- scanners/ios/utility.go
- scanners/ios/utility_test.go
- scanners/macos/macos.go
- scanners/reactnative/plain.go
To allow reusing native iOS project scanning for react-native workflows, extracted project parsing. This includes all filesystem operations.
Resolves: https://bitrise.atlassian.net/browse/STEP-1742
* Extract project scanning from _GenerateOptions()_ into _ParseProjects()_. This way the options are generated from an intermediary representation _DetectResult_. This allows testing the project parsing independently and reusing it in the react-native scanner.
* Remved _Detect()_, merged with _ParseProjects()_
> Seperated iOS Project parsing

- _tests/integration/manual_config_test.go
- _tests/integration/reactnative_test.go
- scanners/reactnative/expo.go
- scanners/reactnative/plain.go
- scanners/reactnative/reactnative.go
- scanners/reactnative/utility.go
- [/] `step.yml` and `README.md` is updated with the changes (if needed)
In case of multiple iOS schemes being present for react-native, duplicate _xcode-archive_ and _deploy-to-bitrise-io_ Steps were generated.
A previous unmerged attampt was #228.
Resolves: https://bitrise.atlassian.net/browse/STEP-1742
- Added iOS config descriptors (missing scheme, podfile) to react-native scanner.
- Added option to select between multiple react-native projects. For Expo this is not supported.
> Fix for react-native workflow duplicate Steps

- scanners/ios/utility.go
- scanners/ios/utility_test.go
Restore previous working directory in the iOS scanner.
This bug in addition to using a different search directory (not the root one, but for example React Native scanner looking for Android projects in the `android` directory) would have broken other (e.g. Fastlane) scanners.
> Restore working directory

- scanner/unknown.go
- scanner/unknown_test.go
Detect unsupported tools/frameworks/platforms in the project directory to log them later.
- Create `scanner/unknown.go` for everything related to scanning the repo for unsupported but recognized tools. This is not a scanner though, because it needs to run only after all other platform scanners fail.
- A common interface for the various tool detectors and 3 actual implementations:
- `singleFileToolDetector` that looks for only a single file name
- `multiFileToolDetector` that first looks for a primary file name, but can also find one of the optional files as a fallback
- `kotlinMultiplatformDetector` because there is no distinct file name pattern for KMM, so it also looks at the file contents of certain files 🤷 
- While traversing the folders recursively, the detectors also build a string …
> Detect unsupported tools in projects

- scanner/result.go
- scanner/tool_detector.go
- scanner/tool_detector_test.go
In #237 we added the ability to detect tools/frameworks that are not yet supported. This PR builds on that to run those tool detectors while scanning the project config and log any detected tool remotely.
- Run the list of tool detectors in `scanner/result.go`, regardless of the scan result
- Use `analytics.LogInfo()` to log any detected tools
- Remove some debug log statements from the previous PR as I discovered that debug logs are enabled globally for the entire `bitrise-init` tool
> Log detected tools

- scanners/ios/utility.go
When `mergePodWorkspaceProjectMap()` returns with a non-nil error, the returned result type unconditionally overwrites the detected containers. This means that the detected containers will be empty and the project won't be recognized as an iOS project at all.
An error in the Cocoapods-related scanning shouldn't cause this, the scanner can still recognize the project's platform correctly, as well as find workspaces and schemes.
> Handle Cocoapods parsing errors gracefully

- _tests/integration/android_test.go
- _tests/integration/cordova_test.go
- _tests/integration/fastlane_test.go
- _tests/integration/flutter_test.go
- _tests/integration/helper/execution.go
- _tests/integration/ionic_test.go
- _tests/integration/ios_test.go
- _tests/integration/mac_test.go
- _tests/integration/manual_config_test.go
- _tests/integration/reactnative_expo_test.go
- _tests/integration/reactnative_test.go
- scanners/android/utility.go
- scanners/fastlane/fastlane.go
- scanners/flutter/flutter.go
- scanners/ios/utility.go
- scanners/ios/workflow.go
- scanners/reactnative/expo.go
- scanners/reactnative/plain.go
- steps/cachesteps.go
- steps/const.go
- steps/steps.go
- Functional
- Replace Cache Pull/Push steps in Android workflows with Restore/Save Gradle cache
- Replace Cache Pull/Push steps in iOS workflows with Restore/Save Cocoapods/Carthage cache
- Remove cache steps from`deploy` workflows. Deploying to stores should probably run a clean build to maximize reproducibility and stability.
- Refactors and cleanups
- Remove dummy comments on exported methods
- Test cleanups
Adding SPM cache steps. This needs new detection logic, but this PR is already large, so it will come in a future PR.
Other platforms are also out of scope for this PR.
> New cache steps for Android & iOS

- _tests/integration/cordova_test.go
- _tests/integration/fastlane_test.go
- _tests/integration/ionic_test.go
- _tests/integration/manual_config_test.go
- _tests/integration/reactnative_expo_test.go
- _tests/integration/reactnative_test.go
- scanners/cordova/cordova.go
- scanners/ionic/ionic.go
- scanners/reactnative/expo.go
- scanners/reactnative/plain.go
- steps/cachesteps.go
- steps/const.go
- steps/steps.go
Add NPM cache steps to:
- React Native and Expo workflows
- Cordova workflows
- Ionic workflows
NPM and Yarn steps have a legacy caching input, but both of them are off by default, so this PR doesn't add those inputs to the workflow.
> Add NPM cache to JS platform workflows

- steps/const.go
Version 8 was a special release, there is no breaking change that we need to handle in the workflows.
https://github.com/bitrise-steplib/steps-git-clone/releases/tag/8.0.0
> Upgrade git-clone to latest major

- _tests/integration/android_test.go
- _tests/integration/cordova_test.go
- _tests/integration/fastlane_test.go
- _tests/integration/flutter_test.go
- _tests/integration/ionic_test.go
- _tests/integration/ios_test.go
- _tests/integration/mac_test.go
- _tests/integration/manual_config_test.go
- _tests/integration/reactnative_expo_test.go
- _tests/integration/reactnative_test.go
- models/configbuilder.go
- models/configbuilder_test.go
The currently generated app config has a trigger map configuration, that triggers two Bitrise builds when a Pull Request gets opened.
This is because the trigger map has a push-type trigger item, which triggers a build for every code push, and another item that triggers a build for every pull request-related event:
```
trigger_map:
- push_branch: '*'
workflow: primary
- pull_request_source_branch: '*'
workflow: primary
```
The expected trigger map triggers a single build when a pull request gets opened (unless you open a PR from the repository default branch) or code gets pushed to the default branch:
```
trigger_map:
- push_branch: <default_branch_name>
workflow: primary
- pull_request_source_branch: '*'
workflow: primary
```
This change couldn't be done on the project-scanner Step side …
> Remove trigger map from the generated configs

- _tests/integration/ios_test.go
- go.mod
- go.sum
- vendor/github.com/bitrise-io/go-xcode/pathfilters/pathfilters.go
- vendor/github.com/bitrise-io/go-xcode/pathfilters/pathfilters_testdata.go
- vendor/github.com/bitrise-io/go-xcode/xcodebuild/build.go
- vendor/github.com/bitrise-io/go-xcode/xcodebuild/resolve_package_deps.go
- vendor/github.com/bitrise-io/go-xcode/xcodebuild/show_build_settings.go
- vendor/github.com/bitrise-io/go-xcode/xcodeproject/xcodeproj/proj.go
- vendor/github.com/bitrise-io/go-xcode/xcodeproject/xcodeproj/recreate_schemes.go
- vendor/github.com/bitrise-io/go-xcode/xcodeproject/xcodeproj/target.go
- vendor/github.com/bitrise-io/go-xcode/xcodeproject/xcodeproj/xcodeproj.go
- vendor/github.com/bitrise-io/go-xcode/xcodeproject/xcscheme/xcscheme.go
- vendor/github.com/bitrise-io/go-xcode/xcodeproject/xcworkspace/xcworkspace.go
- vendor/modules.txt
This PR adds support for Apple Multiplatform App projects.
More info here: https://github.com/bitrise-io/go-xcode/pull/198
JIRA ticket: https://bitrise.atlassian.net/browse/BIVS-1998
- Pull the latest go-xcode version
- Test Apple Multiplatform App projects
For the sake of simplicity, I just pulled the new go-xcode platform detection logic, this means in the case of an Apple Multiplatform App project, both the iOS and macOS scanner detects the project. The user needs to select either iOS or macOS project type and the config will contain related workflows.
An alternative or future improvement would be providing workflows to test and build both platforms.
> Apple multiplatform app detection

- _tests/integration/fastlane_test.go
- _tests/integration/ios_test.go
- _tests/integration/mac_test.go
- _tests/integration/manual_config_test.go
- _tests/integration/reactnative_test.go
- scanners/ios/ios.go
- scanners/ios/spmproject.go
- scanners/ios/utility.go
- scanners/ios/utility_test.go
- scanners/reactnative/plain.go
This PR adds pure SPM project support to the iOS scanner. The Mac version will come in a separate PR.
A couple of implementation details:
1.) 
The solution uses the built in swift toolchain to get a json output of the project setup:
```
swift package dump-package
```
2.)
The most common use case of the top SPM projects is to have single product in an SPM project which most of the time is a library product. But you can easily define more than one product in your project. 
Lets take this example:
```
...
let package = Package(
name: "CoolFeature",
products: [
.library(name: "CoolFeature",  targets: ["CoolFeature"]),
],
...
)
```
When you initialise an empty package with Swift then it sets the package and product name to the same value similar to the example above. In this case Xcode will …
> [CI-1640] Add SPM project support

- _tests/integration/ios_test.go
- _tests/integration/mac_test.go
- scanners/macos/macos.go
This PR hooks up the Mac scanner with the same SPM logic the iOS scanner has. 
Both the iOS and Mac e2e tests had to be updated because the test SPM project I am using (https://github.com/bitrise-io/sample-spm-project.git) is a universal one supporting all of the platforms. So both the iOS and Mac scanner will detect it and will generate a config.
> [CI-1813] Mac spm project detection

- models/models.go
- scanner/config.go
- scanner/result.go
- scanners/android/android.go
- scanners/cordova/cordova.go
- scanners/fastlane/fastlane.go
- scanners/flutter/flutter.go
- scanners/ionic/ionic.go
- scanners/ios/ios.go
- scanners/ios/utility.go
- scanners/ios/workflow.go
- scanners/macos/macos.go
- scanners/reactnative/expo.go
- scanners/reactnative/plain.go
- scanners/reactnative/reactnative.go
- scanners/scanners.go
- steps/steps.go
Requires a *MINOR* [version update](https://semver.org/)
We had a private repository related naming (`isPrivateRepository`, `models.RepoAccessPrivate`) in the project scanner which is not accurate anymore. This PR is to improve this and prevent confusion. 
In the past we thought about private repos as the ones which needs to be accessed through ssh. This is not accurate anymore because you can have private https based repos too. In the code we had this private repo specific names which in the end only affected the existence of the activate ssh key step. 
The main changes is that I renamed this:
```
type RepoAccess int
const (
// RepoAccessUnknown should be used in generating default configs where the access is unknown
RepoAccessUnknown = iota
RepoAccessPublic
RepoAccessPrivate
)
```
to …
> [CI-1884] Rename private repo naming to ssh key specific

- _tests/integration/manual_config_test.go
- _tests/integration/nodejs_test.go
- scanners/nodejs/nodejs.go
- scanners/nodejs/utiltity.go
- steps/const.go
- steps/steps.go
[CI-4741]
Requires a *MAJOR/MINOR/PATCH* [version update](https://semver.org/)
Bitrise stacks come with asdf pre-installed and it's the recommended tool for managing Node.js. (Stacks also have some Node.js versions available managed by asdf.) Let's use asdf in the default workflows for Node.js projects.
Please note, that we don't have an asdf step, so we used a script step for now. The environment doesn't have the `ASDF_NODEJS_LEGACY_FILE_DYNAMIC_STRATEGY` env var set, so we're setting it for now. (I'm reaching out to environment folks to discuss making this a default so we can remove it later.)
This PR also remove the complexity that comes with identifying and setting a Node.js version ourselves. If the project uses a standard way to pin a Node.js version (setting it in a known config …
> Use asdf to manage Node.js version [CI-4741]

- _tests/integration/kmp_test.go
- _tests/integration/manual_config_test.go
- scanners/kmp/kmp.go
This PR fixes the Kotlin Multiplatform generated configs:
- Add Gradle cache steps to the `ios_build` workflows
- Add `build` Pipeline to the manual config, when both iOS and Android app target presents
> Fix kmp configs
